name: my_calculator
description: A new Flutter project

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  math_expressions: ^2.7.0
  intl: ^0.20.2
  js: ^0.7.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
