name: my_calculator
description: A new Flutter project

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  firebase_core: ^2.32.0
  firebase_auth: ^4.6.0
  cloud_firestore: ^4.6.0
  flutter:
    sdk: flutter
  math_expressions: ^2.7.0
  intl: ^0.20.2
  js: ^0.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
